import type * as TS from 'typescript';

export function createPrismaUtils(ts: typeof TS) {
  /**
   * Returns true if the given declarations have a file name that indicates that it was generated by Prisma
   */
  function isGeneratedPrismaFile(declarations: TS.Declaration[]) {
    return declarations.some((declaration) => {
      const fileName = declaration.getSourceFile().fileName;

      return fileName.includes('.prisma/client') || fileName.includes('generated/prisma');
    });
  }

  function isFloatingPrismaPromise(parent: TS.Node) {
    const isAwaited = ts.isAwaitExpression(parent);
    const isReturnStatement = ts.isReturnStatement(parent);

    const isFloating = !isAwaited && !isReturnStatement;

    return isFloating;
  }

  function isInsidePrismaTransaction(node: TS.Node): boolean {
    let current: TS.Node | undefined = node;

    while (current) {
      if (ts.isArrayLiteralExpression(current)) {
        const parent: TS.Node = current.parent;

        if (
          ts.isCallExpression(parent) &&
          parent.arguments.includes(current) &&
          ts.isPropertyAccessExpression(parent.expression) &&
          parent.expression.name.text === '$transaction'
        ) {
          return true;
        }
      }

      current = current.parent;
    }

    return false;
  }

  return {
    isGeneratedPrismaFile,
    isFloatingPrismaPromise,
    isInsidePrismaTransaction,
  };
}

export type PrismaUtils = ReturnType<typeof createPrismaUtils>;
